# Generated by Django 6.0.2 on 2026-06-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="城市名称")),
                (
                    "province",
                    models.CharField(default="", max_length=50, verbose_name="省份"),
                ),
                ("latitude", models.FloatField(default=0, verbose_name="纬度")),
                ("longitude", models.FloatField(default=0, verbose_name="经度")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市",
                "db_table": "city",
                "ordering": ["province", "name"],
            },
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predict_date", models.DateField(verbose_name="预测日期")),
                (
                    "predicted_high",
                    models.FloatField(default=0, verbose_name="预测最高温(℃)"),
                ),
                (
                    "predicted_low",
                    models.FloatField(default=0, verbose_name="预测最低温(℃)"),
                ),
                (
                    "predicted_condition",
                    models.CharField(
                        default="晴", max_length=20, verbose_name="预测天气状况"
                    ),
                ),
                (
                    "model_accuracy",
                    models.FloatField(default=0, verbose_name="模型准确度"),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="RandomForest", max_length=50, verbose_name="模型名称"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="weather.city",
                        verbose_name="城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "预测结果",
                "verbose_name_plural": "预测结果",
                "db_table": "prediction_result",
                "ordering": ["-predict_date"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "temperature_high",
                    models.IntegerField(default=0, verbose_name="最高气温(℃)"),
                ),
                (
                    "temperature_low",
                    models.IntegerField(default=0, verbose_name="最低气温(℃)"),
                ),
                (
                    "weather_condition",
                    models.CharField(
                        choices=[
                            ("晴", "晴"),
                            ("多云", "多云"),
                            ("阴", "阴"),
                            ("小雨", "小雨"),
                            ("中雨", "中雨"),
                            ("大雨", "大雨"),
                            ("暴雨", "暴雨"),
                            ("小雪", "小雪"),
                            ("中雪", "中雪"),
                            ("大雪", "大雪"),
                            ("雾", "雾"),
                            ("霾", "霾"),
                            ("沙尘", "沙尘"),
                            ("雷阵雨", "雷阵雨"),
                            ("雨夹雪", "雨夹雪"),
                            ("晴转多云", "晴转多云"),
                            ("多云转阴", "多云转阴"),
                        ],
                        default="晴",
                        max_length=20,
                        verbose_name="天气状况",
                    ),
                ),
                (
                    "wind_direction",
                    models.CharField(
                        choices=[
                            ("北风", "北风"),
                            ("东北风", "东北风"),
                            ("东风", "东风"),
                            ("东南风", "东南风"),
                            ("南风", "南风"),
                            ("西南风", "西南风"),
                            ("西风", "西风"),
                            ("西北风", "西北风"),
                            ("无持续风向", "无持续风向"),
                        ],
                        default="无持续风向",
                        max_length=20,
                        verbose_name="风向",
                    ),
                ),
                (
                    "wind_power",
                    models.CharField(default="", max_length=20, verbose_name="风力"),
                ),
                ("aqi", models.IntegerField(default=0, verbose_name="空气质量指数")),
                (
                    "aqi_level",
                    models.CharField(
                        choices=[
                            ("优", "优"),
                            ("良", "良"),
                            ("轻度污染", "轻度污染"),
                            ("中度污染", "中度污染"),
                            ("重度污染", "重度污染"),
                            ("严重污染", "严重污染"),
                        ],
                        default="良",
                        max_length=20,
                        verbose_name="空气质量等级",
                    ),
                ),
                ("humidity", models.FloatField(default=0, verbose_name="相对湿度(%)")),
                (
                    "precipitation",
                    models.FloatField(default=0, verbose_name="降水量(mm)"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="weather.city",
                        verbose_name="城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气数据",
                "verbose_name_plural": "天气数据",
                "db_table": "weather_data",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["city", "date"], name="weather_dat_city_id_efb374_idx"
                    ),
                    models.Index(fields=["date"], name="weather_dat_date_b3710c_idx"),
                ],
                "unique_together": {("city", "date")},
            },
        ),
    ]
