# Generated by Django 6.0.2 on 2026-06-06 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["sort_order", "province", "name"],
                "verbose_name": "城市",
                "verbose_name_plural": "城市",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="is_key",
            field=models.BooleanField(default=False, verbose_name="是否重点城市"),
        ),
        migrations.AddField(
            model_name="city",
            name="level",
            field=models.CharField(
                choices=[
                    ("province", "省级"),
                    ("city", "地级市"),
                    ("district", "区县级"),
                    ("town", "镇级"),
                ],
                default="city",
                max_length=20,
                verbose_name="行政级别",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="weather.city",
                verbose_name="上级行政区",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="city",
            name="province",
            field=models.CharField(default="", max_length=50, verbose_name="所属省份"),
        ),
    ]
