# Generated by Django 6.0.2 on 2026-06-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_alter_city_options_city_is_key_city_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="aqi",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="空气质量指数"
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="aqi_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("优", "优"),
                    ("良", "良"),
                    ("轻度污染", "轻度污染"),
                    ("中度污染", "中度污染"),
                    ("重度污染", "重度污染"),
                    ("严重污染", "严重污染"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="空气质量等级",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name="相对湿度(%)"
            ),
        ),
    ]
