# Generated by Django 6.0.2 on 2026-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_make_aqi_humidity_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="weather_condition",
            field=models.CharField(
                choices=[
                    ("晴", "晴"),
                    ("多云", "多云"),
                    ("阴", "阴"),
                    ("小雨", "小雨"),
                    ("中雨", "中雨"),
                    ("大雨", "大雨"),
                    ("暴雨", "暴雨"),
                    ("小雪", "小雪"),
                    ("中雪", "中雪"),
                    ("大雪", "大雪"),
                    ("冻雨", "冻雨"),
                    ("冰雹", "冰雹"),
                    ("霰", "霰"),
                    ("雾", "雾"),
                    ("霾", "霾"),
                    ("沙尘", "沙尘"),
                    ("雷阵雨", "雷阵雨"),
                    ("雨夹雪", "雨夹雪"),
                    ("晴转多云", "晴转多云"),
                    ("多云转阴", "多云转阴"),
                ],
                default="晴",
                max_length=20,
                verbose_name="天气状况",
            ),
        ),
    ]
