# Generated by Django 6.0.2 on 2026-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0005_add_shower_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionresult",
            name="precip_amount",
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name="预计降水量(mm)"
            ),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="precip_probability",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="降水概率(%)"
            ),
        ),
    ]
